name: Test Google AI Agent

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-agent:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run agent test
        env:
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
        run: |
          echo "Testing Google AI Agent..."
          python - <<'EOF'
          import google.generativeai as genai
          import os

          api_key = os.environ.get("GOOGLE_API_KEY")
          if not api_key:
              raise Exception("Missing GOOGLE_API_KEY secret!")

          genai.configure(api_key=api_key)
          model = genai.GenerativeModel("gemini-1.5-flash")
          response = model.generate_content("Say hello world")
          print("✅ Agent replied:", response.text)
          EOF
